### ISSUE TITLE
Info to get

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/ukbAid#1]
- [x] What is the UK Biobank statement they suggest to include in manuscript for this project? Including number. (@AlisaDK)

**Comment by AlisaDK** [comment]
All publications should include the acknowledgement, “This research has been conducted using data from UK Biobank, a major biomedical database” and where appropriate, include a link to the UK Biobank website: www.ukbiobank.ac.uk
Source: https://www.ukbiobank.ac.uk/media/c4yefr4t/210527-uk-biobank-communications-guidelines.pdf

**Comment by lwjohnst86** [comment]
I think there's also a project number we have to add right? the application number?

**Comment by AlisaDK** [comment]
This is a phrasing often used: "This research has been conducted using the UK Biobank Resource under Application Number XXXXX." Our application number is: 81520.

**Comment by lwjohnst86** [comment]
That's perfect thanks!
