### ISSUE TITLE
Add a fake UKB dataset

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/ukbAid#12]

**Comment by lwjohnst86** [comment]
Could use this: https://github.com/trinker/wakefield to make the fake dataset

**Comment by danielibsen** [comment]
Should we put this on the agenda for next organizers meeting? We can discuss what would be useful to have in such an example dataset of variables.

**Comment by lwjohnst86** [comment]
Given that the RAP vs main UKB data are different, and given the difficulty with gettinng all the data from RAP to simulate something fake, I think I'll close this for now because it is way too complicated to figure out.
