### ISSUE TITLE
create dataset using ukbAid

### ISSUE THREAD

**Issue by arborzhang** [steno-aarhus/ukbAid#51]
When adding variables starting with quotes (e.g., p93, "Systolic blood pressure, manual reading"), the dataset could not be created. The error message received was:
failed to export data: Field name(s) not found: 'p93_i0', 'p94_i0', 'p95_i0'] Please check job logs and error files for more details.
@lwjohnst86

**Comment by arborzhang** [comment]
It looks like there is a limitation in the capacity for extracting variables to UKB RAP, approximately capped at 100 project variables (0 instances). I encountered an error when attempting to add more variables. The dataset could be created if I took out some variables. 
Ideally, I would require more space for around 250 metabolite variables. If there is a possibility to expand this capacity, it would significantly enhance the efficiency of work.
@lwjohnst86

**Comment by arborzhang** [comment]
A general question on how to save the intermediate dataset while working at UKB RAP, especially for different subsets and data transformation. Huge thanks for all the kind help!
@lwjohnst86

**Comment by lwjohnst86** [comment]
Yea, I'll have to look into how RAP handles that and ways to bypass it. Thanks for bringing this up!

**Comment by lwjohnst86** [comment]
I hope with the new changes to the package and using the actual schema now, that this is resolved. But @arborzhang let me know if it isn't and open a new issue.
