### ISSUE TITLE
Create a big picture vignette with image of connections/flow

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/ukbAid#7]

**Comment by danielibsen** [comment]
We could talk about this at one point. I could make it in BioRender. Maybe we also would want to upload the overall process image I made for trello.

**Comment by lwjohnst86** [comment]
What do you think about https://steno-aarhus.github.io/ukbAid/#next-steps for the diagram? I modified it from your image (since we aren't using Trello for application anymore).
